# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_product.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog_add(object):
    def setupUi(self, Dialog_add):
        Dialog_add.setObjectName("Dialog_add")
        Dialog_add.resize(450, 300)
        Dialog_add.setMinimumSize(QtCore.QSize(450, 300))
        Dialog_add.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog_add)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Dialog_add)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.txt_product_name = QtWidgets.QLineEdit(Dialog_add)
        self.txt_product_name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.txt_product_name.setObjectName("txt_product_name")
        self.horizontalLayout.addWidget(self.txt_product_name)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(Dialog_add)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.txt_purchase_price = QtWidgets.QLineEdit(Dialog_add)
        self.txt_purchase_price.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhPreferNumbers)
        self.txt_purchase_price.setInputMask("")
        self.txt_purchase_price.setMaxLength(10)
        self.txt_purchase_price.setObjectName("txt_purchase_price")
        self.horizontalLayout_2.addWidget(self.txt_purchase_price)
        self.label_5 = QtWidgets.QLabel(Dialog_add)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.txt_sales_percent = QtWidgets.QLineEdit(Dialog_add)
        self.txt_sales_percent.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhPreferNumbers)
        self.txt_sales_percent.setText("")
        self.txt_sales_percent.setMaxLength(3)
        self.txt_sales_percent.setObjectName("txt_sales_percent")
        self.horizontalLayout_2.addWidget(self.txt_sales_percent)
        self.label_6 = QtWidgets.QLabel(Dialog_add)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox_accessories = QtWidgets.QCheckBox(Dialog_add)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_accessories.setFont(font)
        self.checkBox_accessories.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_accessories.setObjectName("checkBox_accessories")
        self.verticalLayout.addWidget(self.checkBox_accessories)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(Dialog_add)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.txt_sales_price = QtWidgets.QLineEdit(Dialog_add)
        self.txt_sales_price.setEnabled(False)
        self.txt_sales_price.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhPreferNumbers)
        self.txt_sales_price.setText("")
        self.txt_sales_price.setMaxLength(10)
        self.txt_sales_price.setReadOnly(False)
        self.txt_sales_price.setObjectName("txt_sales_price")
        self.horizontalLayout_4.addWidget(self.txt_sales_price)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_add_save = QtWidgets.QPushButton(Dialog_add)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_add_save.setFont(font)
        self.btn_add_save.setObjectName("btn_add_save")
        self.horizontalLayout_3.addWidget(self.btn_add_save)
        self.btn_add_cancel = QtWidgets.QPushButton(Dialog_add)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_add_cancel.setFont(font)
        self.btn_add_cancel.setObjectName("btn_add_cancel")
        self.horizontalLayout_3.addWidget(self.btn_add_cancel)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Dialog_add)
        QtCore.QMetaObject.connectSlotsByName(Dialog_add)

    def retranslateUi(self, Dialog_add):
        _translate = QtCore.QCoreApplication.translate
        Dialog_add.setWindowTitle(_translate("Dialog_add", "افزودن محصول"))
        self.label.setText(_translate("Dialog_add", "نام محصول : "))
        self.txt_product_name.setPlaceholderText(_translate("Dialog_add", "محصول"))
        self.label_4.setText(_translate("Dialog_add", "قیمت خرید : "))
        self.txt_purchase_price.setPlaceholderText(_translate("Dialog_add", "10000"))
        self.label_5.setText(_translate("Dialog_add", "درصد فروش : "))
        self.txt_sales_percent.setPlaceholderText(_translate("Dialog_add", "20"))
        self.label_6.setText(_translate("Dialog_add", "%"))
        self.checkBox_accessories.setText(_translate("Dialog_add", "ادوات"))
        self.label_7.setText(_translate("Dialog_add", "قیمت فروش : "))
        self.txt_sales_price.setPlaceholderText(_translate("Dialog_add", "20000"))
        self.btn_add_save.setText(_translate("Dialog_add", "ذخیره"))
        self.btn_add_cancel.setText(_translate("Dialog_add", "بیخیال"))

