# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'update_product.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_update_dialog(object):
    def setupUi(self, update_dialog):
        update_dialog.setObjectName("update_dialog")
        update_dialog.resize(450, 300)
        update_dialog.setMinimumSize(QtCore.QSize(450, 300))
        update_dialog.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.verticalLayout = QtWidgets.QVBoxLayout(update_dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtWidgets.QLabel(update_dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.txt_product_id = QtWidgets.QLineEdit(update_dialog)
        self.txt_product_id.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.txt_product_id.setReadOnly(True)
        self.txt_product_id.setObjectName("txt_product_id")
        self.horizontalLayout_8.addWidget(self.txt_product_id)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(update_dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.txt_product_name = QtWidgets.QLineEdit(update_dialog)
        self.txt_product_name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.txt_product_name.setObjectName("txt_product_name")
        self.horizontalLayout.addWidget(self.txt_product_name)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(update_dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.txt_purchase_price = QtWidgets.QLineEdit(update_dialog)
        self.txt_purchase_price.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhPreferNumbers)
        self.txt_purchase_price.setInputMask("")
        self.txt_purchase_price.setMaxLength(11)
        self.txt_purchase_price.setObjectName("txt_purchase_price")
        self.horizontalLayout_2.addWidget(self.txt_purchase_price)
        self.label_5 = QtWidgets.QLabel(update_dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.txt_sales_percent = QtWidgets.QLineEdit(update_dialog)
        self.txt_sales_percent.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhPreferNumbers)
        self.txt_sales_percent.setText("")
        self.txt_sales_percent.setMaxLength(3)
        self.txt_sales_percent.setObjectName("txt_sales_percent")
        self.horizontalLayout_2.addWidget(self.txt_sales_percent)
        self.label_6 = QtWidgets.QLabel(update_dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(update_dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.txt_sales_price = QtWidgets.QLineEdit(update_dialog)
        self.txt_sales_price.setEnabled(True)
        self.txt_sales_price.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhPreferNumbers)
        self.txt_sales_price.setInputMask("")
        self.txt_sales_price.setMaxLength(11)
        self.txt_sales_price.setReadOnly(True)
        self.txt_sales_price.setObjectName("txt_sales_price")
        self.horizontalLayout_5.addWidget(self.txt_sales_price)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_update = QtWidgets.QPushButton(update_dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_update.setFont(font)
        self.btn_update.setObjectName("btn_update")
        self.horizontalLayout_3.addWidget(self.btn_update)
        self.btn_update_cancel = QtWidgets.QPushButton(update_dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_update_cancel.setFont(font)
        self.btn_update_cancel.setObjectName("btn_update_cancel")
        self.horizontalLayout_3.addWidget(self.btn_update_cancel)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(update_dialog)
        QtCore.QMetaObject.connectSlotsByName(update_dialog)

    def retranslateUi(self, update_dialog):
        _translate = QtCore.QCoreApplication.translate
        update_dialog.setWindowTitle(_translate("update_dialog", "ویرایش محصول"))
        self.label_8.setText(_translate("update_dialog", "شناسه محصول : "))
        self.txt_product_id.setPlaceholderText(_translate("update_dialog", "محصول"))
        self.label.setText(_translate("update_dialog", "نام محصول : "))
        self.txt_product_name.setPlaceholderText(_translate("update_dialog", "محصول"))
        self.label_4.setText(_translate("update_dialog", "قیمت خرید : "))
        self.txt_purchase_price.setPlaceholderText(_translate("update_dialog", "123456"))
        self.label_5.setText(_translate("update_dialog", "درصد فروش : "))
        self.txt_sales_percent.setPlaceholderText(_translate("update_dialog", "20"))
        self.label_6.setText(_translate("update_dialog", "%"))
        self.label_7.setText(_translate("update_dialog", "قیمت فروش : "))
        self.txt_sales_price.setPlaceholderText(_translate("update_dialog", "123456"))
        self.btn_update.setText(_translate("update_dialog", "ویرایش"))
        self.btn_update_cancel.setText(_translate("update_dialog", "بیخیال"))

